// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pierbin/screechr/cmd/router"
	"github.com/pierbin/screechr/internal/config"
	"github.com/pierbin/screechr/internal/controller"
	"github.com/pierbin/screechr/internal/repo"
)

// Injectors from wire.go:

func Initializing() *router.Router {
	configConfig := config.NewConfig()
	screechrRepo := repo.NewScreechrRepo(configConfig)
	screechrCtl := controller.NewScreechrCtl(screechrRepo)
	handler := router.NewHandler(screechrCtl)
	routerRouter := router.NewRouter(handler)
	return routerRouter
}
